### ISSUE TITLE
Replace python-coveralls with more actively maintained coveralls

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#358]
The `coverage` package significantly changed API with the release of [v5.0](https://coverage.readthedocs.io/en/coverage-5.0.3/whatsnew5x.html). However, the python package we use to interface with coveralls.io (`python-coveralls`) hasn't incorporated these changes. This leads to the exception below in our TravisCi builds:

```python
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/rsmenv/bin/coveralls", line 8, in <module>
    sys.exit(wear())
  File "/home/travis/miniconda3/envs/rsmenv/lib/python3.7/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/miniconda3/envs/rsmenv/lib/python3.7/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/miniconda3/envs/rsmenv/lib/python3.7/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/travis/miniconda3/envs/rsmenv/lib/python3.7/site-packages/coverage/report.py)
```

We should replace `python-coveralls` with the more actively maintained package [`coveralls`](https://pypi.org/project/coveralls/).

**Comment by desilinguist** [comment]
Addressed by #349.
