### ISSUE TITLE
Switch CI build to use Python 3.7

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/rsmtool#494]
`xlrd` has dropped support for XLSX files starting with v2.0. Therefore, when using an XLSX file as input, the current RSMTool package will raise the following error:

```python

Traceback (most recent call last):
  File "/private/scratch/nmadnani/rsmtool/rsmdev/bin/rsmtool", line 33, in <module>
    sys.exit(load_entry_point('rsmtool', 'console_scripts', 'rsmtool')())
  File "/private/scratch/nmadnani/rsmtool/rsmtool/rsmtool.py", line 372, in main
    run_experiment(abspath(args.config_file),
  File "/private/scratch/nmadnani/rsmtool/rsmtool/rsmtool.py", line 145, in run_experiment
    data_container = reader.read()
  File "/private/scratch/nmadnani/rsmtool/rsmtool/reader.py", line 370, in read
    dataframe = self.read_from_file(set_path, converter, **kwargs)
  File "/private/scratch/nmadnani/rsmtool/rsmtool/reader.py", line 263, in read_from_file
    df = do_read(filename, **kwargs)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 304, in read_excel         sh %s'
    io = ExcelFile(io, engine=engine)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 867, in __init__
    self._reader = self._engines[engine](self._io)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 22, in __init__
    super().__init__(filepath_or_buffer)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 353, in __init__
    self.book = self.load_workbook(filepath_or_buffer)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/pandas/io/excel/_xlrd.py", line 37, in load_workbook
    return open_workbook(filepath_or_buffer)
  File "/private/scratch/nmadnani/rsmtool/rsmdev/lib/python3.8/site-packages/xlrd/__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported
```

**Comment by desilinguist** [comment]
It [looks like](http://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel) `pandas.read_excel()` should use `openpyxl` automatically if it is installed and needed.

**Comment by desilinguist** [comment]
Confirmed! There is a very simple workaround for this error. Just update `pandas` to v1.2.0 or higher:

```
conda install pandas=1.2.0
```

This works because `openpyxl` is already installed as a dependency.

**Comment by desilinguist** [comment]
A longer-term fix would be to pin `pandas` to v1.2.0 or higher. However, it is not really necessary, because `pandas` is already unpinned.

**Comment by desilinguist** [comment]
The reason that the Travis CI build failed is because conda-forge currently has no conda package for `pandas=1.2.0` for Python 3.6. 

```bash
$> conda search -c conda-forge pandas=1.2.0
Loading channels: done
# Name                       Version           Build  Channel             
pandas                         1.2.0  py37hdc94413_0  conda-forge         
pandas                         1.2.0  py38h51da96c_0  conda-forge         
pandas                         1.2.0  py39hde0f152_0  conda-forge
```

I am hoping this is a temporary issue.  If it isn't, we will have a bigger issue on our hands. Let's see what happens with the next scheduled `stable` build.

**Comment by desilinguist** [comment]
Done in #498 and #499.
