### ISSUE TITLE
Error during rsmeval: `RuntimeError: Kernel died before replying to kernel_info`

### ISSUE THREAD

**Issue by bwriordan** [EducationalTestingService/rsmtool#66]
Below is the relevant context from our output. This might be a jupyter_client issue.

This seems to be intermittent: it only happened once among 7 datasets. This dataset has had rsmeval work on its output without problem in the past.

```python
INFO:rsmtool.rsmeval:Processing predictions
INFO:rsmtool.rsmeval:Saving pre-processed predictions and the metadata to disk
INFO:rsmtool.rsmeval:Running analyses on predictions
INFO:rsmtool.rsmeval:Starting report generation
INFO:rsmtool.report:Merging sections
INFO:rsmtool.report:Exporting HTML
INFO:root:Executing notebook with kernel: python3
INFO:rsmtool.rsmeval:Assuming given system predictions are unscaled and will be used as such.
INFO:rsmtool.rsmeval:Reading predictions: [...]
INFO:rsmtool.rsmeval:Processing predictions
INFO:rsmtool.rsmeval:Saving pre-processed predictions and the metadata to disk
INFO:rsmtool.rsmeval:Running analyses on predictions
INFO:rsmtool.rsmeval:Starting report generation
INFO:rsmtool.report:Merging sections
INFO:rsmtool.report:Exporting HTML
INFO:root:Executing notebook with kernel: python3
Traceback (most recent call last):
  [...]
  File "/opt/python/rsmtool/lib/python3.4/site-packages/rsmtool/rsmeval.py", line 485, in run_evaluation
    context='rsmeval')
  File "/opt/python/rsmtool/lib/python3.4/site-packages/rsmtool/report.py", line 513, in create_report
    join(reportdir, '{}.html'.format(report_name)))
  File "/opt/python/rsmtool/lib/python3.4/site-packages/rsmtool/report.py", line 592, in convert_ipynb_to_html
    output, resources = exportHtml.from_filename(notebook_file)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/templateexporter.py", line 200, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/nbconvert/preprocessors/execute.py", line 141, in preprocess
    cwd=path)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/jupyter_client/manager.py", line 433, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/opt/python/rsmtool/lib/python3.4/site-packages/jupyter_client/blocking/client.py", line 59, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info
```

**Comment by desilinguist** [comment]
Do you get the same error if you simply re-run `rsmtool`? 

It's unlikely that this is a real timeout which means that you have so much data that it would take more than an hour (the current timeout setting) to generate the graphs in the report. More likely, it's one of those weird errors that happen when generating notebooks dynamically with the IPython kernel.

**Comment by aloukina** [comment]
This can also sometimes happen when two instances of Jupyter server are running at the same time (e.g. in two different tabs).

**Comment by desilinguist** [comment]
I am going to close this for now.
